// Opens a print-ready window with a formatted checklist. Client-only.

export interface PrintChecklistOptions {
  title: string;
  vendor?: string;
  meta?: string[];
  items: string[];
  notes?: string;
}

export function printChecklist(opts: PrintChecklistOptions) {
  if (typeof window === "undefined") return;
  const { title, vendor, meta = [], items, notes } = opts;
  const esc = (s: string) =>
    s.replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));

  const html = `<!doctype html>
<html><head><meta charset="utf-8"><title>${esc(title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #0b0f17; margin: 40px; }
  h1 { font-size: 22px; margin: 0 0 4px; }
  .vendor { color: #475569; font-size: 13px; margin-bottom: 16px; }
  .meta { display: flex; flex-wrap: wrap; gap: 8px 16px; font-size: 12px; color: #334155; border-top: 1px solid #e2e8f0; border-bottom: 1px solid #e2e8f0; padding: 10px 0; margin-bottom: 24px; }
  ol { padding: 0; margin: 0; list-style: none; }
  li { display: flex; gap: 12px; align-items: flex-start; padding: 10px 0; border-bottom: 1px dashed #cbd5e1; font-size: 14px; }
  .box { width: 18px; height: 18px; border: 1.5px solid #0b0f17; border-radius: 3px; flex-shrink: 0; margin-top: 1px; }
  .num { color: #64748b; width: 20px; font-variant-numeric: tabular-nums; }
  .notes { margin-top: 24px; padding: 12px 14px; background: #fef3c7; border-left: 3px solid #f59e0b; font-size: 13px; }
  .foot { margin-top: 32px; font-size: 11px; color: #94a3b8; text-align: center; }
  @media print { body { margin: 20mm; } .noprint { display: none; } }
  .noprint { position: fixed; top: 12px; right: 12px; }
  button { background: #10b981; color: white; border: 0; padding: 8px 14px; border-radius: 6px; font-size: 13px; cursor: pointer; }
</style></head>
<body>
  <div class="noprint"><button onclick="window.print()">Print</button></div>
  <h1>${esc(title)}</h1>
  ${vendor ? `<div class="vendor">Prepared by ${esc(vendor)}</div>` : ""}
  ${meta.length ? `<div class="meta">${meta.map((m) => `<span>${esc(m)}</span>`).join("")}</div>` : ""}
  <ol>
    ${items.map((it, i) => `<li><span class="num">${i + 1}.</span><span class="box"></span><span>${esc(it)}</span></li>`).join("")}
  </ol>
  ${notes ? `<div class="notes"><strong>Notes:</strong> ${esc(notes)}</div>` : ""}
  <div class="foot">Generated by GlobeTrek PK · ${new Date().toLocaleDateString()}</div>
  <script>window.addEventListener("load", () => setTimeout(() => window.print(), 300));</script>
</body></html>`;

  const w = window.open("", "_blank", "width=800,height=900");
  if (!w) return;
  w.document.open();
  w.document.write(html);
  w.document.close();
}
