/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AffiliateRouteImport } from './routes/affiliate'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeAffiliateRouteImport } from './routes/become-affiliate'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CustomTourRouteImport } from './routes/custom-tour'
import { Route as CustomVisaRouteImport } from './routes/custom-visa'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as ToursRouteImport } from './routes/tours'
import { Route as VendorGuideRouteImport } from './routes/vendor-guide'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVendorRouteImport } from './routes/_authenticated/vendor'
import { Route as ApiAiChatRouteImport } from './routes/api/ai-chat'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as CustomerQuotesRouteImport } from './routes/customer.quotes'
import { Route as CustomerVisaQuotesRouteImport } from './routes/customer.visa-quotes'
import { Route as InsuranceIndexRouteImport } from './routes/insurance.index'
import { Route as InsuranceIdRouteImport } from './routes/insurance.$id'
import { Route as TicketsIndexRouteImport } from './routes/tickets.index'
import { Route as TicketsIdRouteImport } from './routes/tickets.$id'
import { Route as ToursIndexRouteImport } from './routes/tours.index'
import { Route as ToursIdRouteImport } from './routes/tours.$id'
import { Route as VisaIndexRouteImport } from './routes/visa.index'
import { Route as VisaIdRouteImport } from './routes/visa.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminAffiliatePayoutsRouteImport } from './routes/_authenticated/admin.affiliate-payouts'
import { Route as AuthenticatedAdminAffiliatesRouteImport } from './routes/_authenticated/admin.affiliates'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedAdminCustomLeadsRouteImport } from './routes/_authenticated/admin.custom-leads'
import { Route as AuthenticatedAdminCustomVisaRouteImport } from './routes/_authenticated/admin.custom-visa'
import { Route as AuthenticatedAdminFinancialsRouteImport } from './routes/_authenticated/admin.financials'
import { Route as AuthenticatedAdminKycCmsRouteImport } from './routes/_authenticated/admin.kyc-cms'
import { Route as AuthenticatedAdminLandingCmsRouteImport } from './routes/_authenticated/admin.landing-cms'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin.leads'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminSeoRouteImport } from './routes/_authenticated/admin.seo'
import { Route as AuthenticatedAdminServicesRouteImport } from './routes/_authenticated/admin.services'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminToursRouteImport } from './routes/_authenticated/admin.tours'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminVendorGuideRouteImport } from './routes/_authenticated/admin.vendor-guide'
import { Route as AuthenticatedAdminVendorsRouteImport } from './routes/_authenticated/admin.vendors'
import { Route as AuthenticatedAdminWhatsappRouteImport } from './routes/_authenticated/admin.whatsapp'
import { Route as AuthenticatedCustomerIndexRouteImport } from './routes/_authenticated/customer.index'
import { Route as AuthenticatedVendorIndexRouteImport } from './routes/_authenticated/vendor.index'
import { Route as AuthenticatedVendorBillingRouteImport } from './routes/_authenticated/vendor.billing'
import { Route as AuthenticatedVendorCustomLeadsRouteImport } from './routes/_authenticated/vendor.custom-leads'
import { Route as AuthenticatedVendorCustomVisaLeadsRouteImport } from './routes/_authenticated/vendor.custom-visa-leads'
import { Route as AuthenticatedVendorInsuranceRouteImport } from './routes/_authenticated/vendor.insurance'
import { Route as AuthenticatedVendorInvoicesRouteImport } from './routes/_authenticated/vendor.invoices'
import { Route as AuthenticatedVendorKycRouteImport } from './routes/_authenticated/vendor.kyc'
import { Route as AuthenticatedVendorLeadsRouteImport } from './routes/_authenticated/vendor.leads'
import { Route as AuthenticatedVendorServicesRouteImport } from './routes/_authenticated/vendor.services'
import { Route as AuthenticatedVendorTicketsRouteImport } from './routes/_authenticated/vendor.tickets'
import { Route as AuthenticatedVendorToursRouteImport } from './routes/_authenticated/vendor.tours'
import { Route as AuthenticatedVendorVisaRouteImport } from './routes/_authenticated/vendor.visa'
import { Route as ApiAuthRegisterRouteImport } from './routes/api/auth.register'
import { Route as ApiCronSubscriptionsRouteImport } from './routes/api/cron/subscriptions'
import { Route as ApiPublicSafepayWebhookRouteImport } from './routes/api/public/safepay-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateRoute = AffiliateRouteImport.update({
  id: '/affiliate',
  path: '/affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAffiliateRoute = BecomeAffiliateRouteImport.update({
  id: '/become-affiliate',
  path: '/become-affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomTourRoute = CustomTourRouteImport.update({
  id: '/custom-tour',
  path: '/custom-tour',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomVisaRoute = CustomVisaRouteImport.update({
  id: '/custom-visa',
  path: '/custom-visa',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursRoute = ToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorGuideRoute = VendorGuideRouteImport.update({
  id: '/vendor-guide',
  path: '/vendor-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendorRoute = AuthenticatedVendorRouteImport.update({
  id: '/vendor',
  path: '/vendor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAiChatRoute = ApiAiChatRouteImport.update({
  id: '/api/ai-chat',
  path: '/api/ai-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerQuotesRoute = CustomerQuotesRouteImport.update({
  id: '/customer/quotes',
  path: '/customer/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerVisaQuotesRoute = CustomerVisaQuotesRouteImport.update({
  id: '/customer/visa-quotes',
  path: '/customer/visa-quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceIndexRoute = InsuranceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InsuranceRoute,
} as any)
const InsuranceIdRoute = InsuranceIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InsuranceRoute,
} as any)
const TicketsIndexRoute = TicketsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TicketsRoute,
} as any)
const TicketsIdRoute = TicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TicketsRoute,
} as any)
const ToursIndexRoute = ToursIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ToursRoute,
} as any)
const ToursIdRoute = ToursIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ToursRoute,
} as any)
const VisaIndexRoute = VisaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VisaRoute,
} as any)
const VisaIdRoute = VisaIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => VisaRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAffiliatePayoutsRoute =
  AuthenticatedAdminAffiliatePayoutsRouteImport.update({
    id: '/affiliate-payouts',
    path: '/affiliate-payouts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAffiliatesRoute =
  AuthenticatedAdminAffiliatesRouteImport.update({
    id: '/affiliates',
    path: '/affiliates',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCustomLeadsRoute =
  AuthenticatedAdminCustomLeadsRouteImport.update({
    id: '/custom-leads',
    path: '/custom-leads',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomVisaRoute =
  AuthenticatedAdminCustomVisaRouteImport.update({
    id: '/custom-visa',
    path: '/custom-visa',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminFinancialsRoute =
  AuthenticatedAdminFinancialsRouteImport.update({
    id: '/financials',
    path: '/financials',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminKycCmsRoute =
  AuthenticatedAdminKycCmsRouteImport.update({
    id: '/kyc-cms',
    path: '/kyc-cms',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLandingCmsRoute =
  AuthenticatedAdminLandingCmsRouteImport.update({
    id: '/landing-cms',
    path: '/landing-cms',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSeoRoute = AuthenticatedAdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminServicesRoute =
  AuthenticatedAdminServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminToursRoute = AuthenticatedAdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVendorGuideRoute =
  AuthenticatedAdminVendorGuideRouteImport.update({
    id: '/vendor-guide',
    path: '/vendor-guide',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminVendorsRoute =
  AuthenticatedAdminVendorsRouteImport.update({
    id: '/vendors',
    path: '/vendors',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWhatsappRoute =
  AuthenticatedAdminWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedCustomerIndexRoute =
  AuthenticatedCustomerIndexRouteImport.update({
    id: '/customer/',
    path: '/customer/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendorIndexRoute =
  AuthenticatedVendorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorBillingRoute =
  AuthenticatedVendorBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorCustomLeadsRoute =
  AuthenticatedVendorCustomLeadsRouteImport.update({
    id: '/custom-leads',
    path: '/custom-leads',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorCustomVisaLeadsRoute =
  AuthenticatedVendorCustomVisaLeadsRouteImport.update({
    id: '/custom-visa-leads',
    path: '/custom-visa-leads',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorInsuranceRoute =
  AuthenticatedVendorInsuranceRouteImport.update({
    id: '/insurance',
    path: '/insurance',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorInvoicesRoute =
  AuthenticatedVendorInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorKycRoute = AuthenticatedVendorKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AuthenticatedVendorRoute,
} as any)
const AuthenticatedVendorLeadsRoute =
  AuthenticatedVendorLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorServicesRoute =
  AuthenticatedVendorServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorTicketsRoute =
  AuthenticatedVendorTicketsRouteImport.update({
    id: '/tickets',
    path: '/tickets',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorToursRoute =
  AuthenticatedVendorToursRouteImport.update({
    id: '/tours',
    path: '/tours',
    getParentRoute: () => AuthenticatedVendorRoute,
  } as any)
const AuthenticatedVendorVisaRoute = AuthenticatedVendorVisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => AuthenticatedVendorRoute,
} as any)
const ApiAuthRegisterRoute = ApiAuthRegisterRouteImport.update({
  id: '/api/auth/register',
  path: '/api/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSubscriptionsRoute = ApiCronSubscriptionsRouteImport.update({
  id: '/api/cron/subscriptions',
  path: '/api/cron/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSafepayWebhookRoute = ApiPublicSafepayWebhookRouteImport.update({
  id: '/api/public/safepay-webhook',
  path: '/api/public/safepay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/become-affiliate': typeof BecomeAffiliateRoute
  '/compare': typeof CompareRoute
  '/custom-tour': typeof CustomTourRoute
  '/custom-visa': typeof CustomVisaRoute
  '/destinations': typeof DestinationsRoute
  '/enterprise': typeof EnterpriseRoute
  '/insurance': typeof InsuranceRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/tours': typeof ToursRouteWithChildren
  '/vendor-guide': typeof VendorGuideRoute
  '/visa': typeof VisaRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/vendor': typeof AuthenticatedVendorRouteWithChildren
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/customer/quotes': typeof CustomerQuotesRoute
  '/customer/visa-quotes': typeof CustomerVisaQuotesRoute
  '/insurance/$id': typeof InsuranceIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tours/$id': typeof ToursIdRoute
  '/visa/$id': typeof VisaIdRoute
  '/insurance/': typeof InsuranceIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/visa/': typeof VisaIndexRoute
  '/admin/affiliate-payouts': typeof AuthenticatedAdminAffiliatePayoutsRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/custom-leads': typeof AuthenticatedAdminCustomLeadsRoute
  '/admin/custom-visa': typeof AuthenticatedAdminCustomVisaRoute
  '/admin/financials': typeof AuthenticatedAdminFinancialsRoute
  '/admin/kyc-cms': typeof AuthenticatedAdminKycCmsRoute
  '/admin/landing-cms': typeof AuthenticatedAdminLandingCmsRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/tours': typeof AuthenticatedAdminToursRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vendor-guide': typeof AuthenticatedAdminVendorGuideRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/vendor/billing': typeof AuthenticatedVendorBillingRoute
  '/vendor/custom-leads': typeof AuthenticatedVendorCustomLeadsRoute
  '/vendor/custom-visa-leads': typeof AuthenticatedVendorCustomVisaLeadsRoute
  '/vendor/insurance': typeof AuthenticatedVendorInsuranceRoute
  '/vendor/invoices': typeof AuthenticatedVendorInvoicesRoute
  '/vendor/kyc': typeof AuthenticatedVendorKycRoute
  '/vendor/leads': typeof AuthenticatedVendorLeadsRoute
  '/vendor/services': typeof AuthenticatedVendorServicesRoute
  '/vendor/tickets': typeof AuthenticatedVendorTicketsRoute
  '/vendor/tours': typeof AuthenticatedVendorToursRoute
  '/vendor/visa': typeof AuthenticatedVendorVisaRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/cron/subscriptions': typeof ApiCronSubscriptionsRoute
  '/api/public/safepay-webhook': typeof ApiPublicSafepayWebhookRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/customer/': typeof AuthenticatedCustomerIndexRoute
  '/vendor/': typeof AuthenticatedVendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/become-affiliate': typeof BecomeAffiliateRoute
  '/compare': typeof CompareRoute
  '/custom-tour': typeof CustomTourRoute
  '/custom-visa': typeof CustomVisaRoute
  '/destinations': typeof DestinationsRoute
  '/enterprise': typeof EnterpriseRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vendor-guide': typeof VendorGuideRoute
  '/wishlist': typeof WishlistRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/customer/quotes': typeof CustomerQuotesRoute
  '/customer/visa-quotes': typeof CustomerVisaQuotesRoute
  '/insurance/$id': typeof InsuranceIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tours/$id': typeof ToursIdRoute
  '/visa/$id': typeof VisaIdRoute
  '/insurance': typeof InsuranceIndexRoute
  '/tickets': typeof TicketsIndexRoute
  '/tours': typeof ToursIndexRoute
  '/visa': typeof VisaIndexRoute
  '/admin/affiliate-payouts': typeof AuthenticatedAdminAffiliatePayoutsRoute
  '/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/custom-leads': typeof AuthenticatedAdminCustomLeadsRoute
  '/admin/custom-visa': typeof AuthenticatedAdminCustomVisaRoute
  '/admin/financials': typeof AuthenticatedAdminFinancialsRoute
  '/admin/kyc-cms': typeof AuthenticatedAdminKycCmsRoute
  '/admin/landing-cms': typeof AuthenticatedAdminLandingCmsRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/admin/services': typeof AuthenticatedAdminServicesRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/tours': typeof AuthenticatedAdminToursRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/vendor-guide': typeof AuthenticatedAdminVendorGuideRoute
  '/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/vendor/billing': typeof AuthenticatedVendorBillingRoute
  '/vendor/custom-leads': typeof AuthenticatedVendorCustomLeadsRoute
  '/vendor/custom-visa-leads': typeof AuthenticatedVendorCustomVisaLeadsRoute
  '/vendor/insurance': typeof AuthenticatedVendorInsuranceRoute
  '/vendor/invoices': typeof AuthenticatedVendorInvoicesRoute
  '/vendor/kyc': typeof AuthenticatedVendorKycRoute
  '/vendor/leads': typeof AuthenticatedVendorLeadsRoute
  '/vendor/services': typeof AuthenticatedVendorServicesRoute
  '/vendor/tickets': typeof AuthenticatedVendorTicketsRoute
  '/vendor/tours': typeof AuthenticatedVendorToursRoute
  '/vendor/visa': typeof AuthenticatedVendorVisaRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/cron/subscriptions': typeof ApiCronSubscriptionsRoute
  '/api/public/safepay-webhook': typeof ApiPublicSafepayWebhookRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/customer': typeof AuthenticatedCustomerIndexRoute
  '/vendor': typeof AuthenticatedVendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/affiliate': typeof AffiliateRoute
  '/auth': typeof AuthRoute
  '/become-affiliate': typeof BecomeAffiliateRoute
  '/compare': typeof CompareRoute
  '/custom-tour': typeof CustomTourRoute
  '/custom-visa': typeof CustomVisaRoute
  '/destinations': typeof DestinationsRoute
  '/enterprise': typeof EnterpriseRoute
  '/insurance': typeof InsuranceRouteWithChildren
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/tickets': typeof TicketsRouteWithChildren
  '/tours': typeof ToursRouteWithChildren
  '/vendor-guide': typeof VendorGuideRoute
  '/visa': typeof VisaRouteWithChildren
  '/wishlist': typeof WishlistRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/vendor': typeof AuthenticatedVendorRouteWithChildren
  '/api/ai-chat': typeof ApiAiChatRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/customer/quotes': typeof CustomerQuotesRoute
  '/customer/visa-quotes': typeof CustomerVisaQuotesRoute
  '/insurance/$id': typeof InsuranceIdRoute
  '/tickets/$id': typeof TicketsIdRoute
  '/tours/$id': typeof ToursIdRoute
  '/visa/$id': typeof VisaIdRoute
  '/insurance/': typeof InsuranceIndexRoute
  '/tickets/': typeof TicketsIndexRoute
  '/tours/': typeof ToursIndexRoute
  '/visa/': typeof VisaIndexRoute
  '/_authenticated/admin/affiliate-payouts': typeof AuthenticatedAdminAffiliatePayoutsRoute
  '/_authenticated/admin/affiliates': typeof AuthenticatedAdminAffiliatesRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/custom-leads': typeof AuthenticatedAdminCustomLeadsRoute
  '/_authenticated/admin/custom-visa': typeof AuthenticatedAdminCustomVisaRoute
  '/_authenticated/admin/financials': typeof AuthenticatedAdminFinancialsRoute
  '/_authenticated/admin/kyc-cms': typeof AuthenticatedAdminKycCmsRoute
  '/_authenticated/admin/landing-cms': typeof AuthenticatedAdminLandingCmsRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/seo': typeof AuthenticatedAdminSeoRoute
  '/_authenticated/admin/services': typeof AuthenticatedAdminServicesRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/tours': typeof AuthenticatedAdminToursRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/vendor-guide': typeof AuthenticatedAdminVendorGuideRoute
  '/_authenticated/admin/vendors': typeof AuthenticatedAdminVendorsRoute
  '/_authenticated/admin/whatsapp': typeof AuthenticatedAdminWhatsappRoute
  '/_authenticated/vendor/billing': typeof AuthenticatedVendorBillingRoute
  '/_authenticated/vendor/custom-leads': typeof AuthenticatedVendorCustomLeadsRoute
  '/_authenticated/vendor/custom-visa-leads': typeof AuthenticatedVendorCustomVisaLeadsRoute
  '/_authenticated/vendor/insurance': typeof AuthenticatedVendorInsuranceRoute
  '/_authenticated/vendor/invoices': typeof AuthenticatedVendorInvoicesRoute
  '/_authenticated/vendor/kyc': typeof AuthenticatedVendorKycRoute
  '/_authenticated/vendor/leads': typeof AuthenticatedVendorLeadsRoute
  '/_authenticated/vendor/services': typeof AuthenticatedVendorServicesRoute
  '/_authenticated/vendor/tickets': typeof AuthenticatedVendorTicketsRoute
  '/_authenticated/vendor/tours': typeof AuthenticatedVendorToursRoute
  '/_authenticated/vendor/visa': typeof AuthenticatedVendorVisaRoute
  '/api/auth/register': typeof ApiAuthRegisterRoute
  '/api/cron/subscriptions': typeof ApiCronSubscriptionsRoute
  '/api/public/safepay-webhook': typeof ApiPublicSafepayWebhookRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/customer/': typeof AuthenticatedCustomerIndexRoute
  '/_authenticated/vendor/': typeof AuthenticatedVendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affiliate'
    | '/auth'
    | '/become-affiliate'
    | '/compare'
    | '/custom-tour'
    | '/custom-visa'
    | '/destinations'
    | '/enterprise'
    | '/insurance'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/tickets'
    | '/tours'
    | '/vendor-guide'
    | '/visa'
    | '/wishlist'
    | '/admin'
    | '/dashboard'
    | '/vendor'
    | '/api/ai-chat'
    | '/api/sitemap.xml'
    | '/customer/quotes'
    | '/customer/visa-quotes'
    | '/insurance/$id'
    | '/tickets/$id'
    | '/tours/$id'
    | '/visa/$id'
    | '/insurance/'
    | '/tickets/'
    | '/tours/'
    | '/visa/'
    | '/admin/affiliate-payouts'
    | '/admin/affiliates'
    | '/admin/ai'
    | '/admin/custom-leads'
    | '/admin/custom-visa'
    | '/admin/financials'
    | '/admin/kyc-cms'
    | '/admin/landing-cms'
    | '/admin/leads'
    | '/admin/payments'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/subscriptions'
    | '/admin/tours'
    | '/admin/users'
    | '/admin/vendor-guide'
    | '/admin/vendors'
    | '/admin/whatsapp'
    | '/vendor/billing'
    | '/vendor/custom-leads'
    | '/vendor/custom-visa-leads'
    | '/vendor/insurance'
    | '/vendor/invoices'
    | '/vendor/kyc'
    | '/vendor/leads'
    | '/vendor/services'
    | '/vendor/tickets'
    | '/vendor/tours'
    | '/vendor/visa'
    | '/api/auth/register'
    | '/api/cron/subscriptions'
    | '/api/public/safepay-webhook'
    | '/admin/'
    | '/customer/'
    | '/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affiliate'
    | '/auth'
    | '/become-affiliate'
    | '/compare'
    | '/custom-tour'
    | '/custom-visa'
    | '/destinations'
    | '/enterprise'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/vendor-guide'
    | '/wishlist'
    | '/dashboard'
    | '/api/ai-chat'
    | '/api/sitemap.xml'
    | '/customer/quotes'
    | '/customer/visa-quotes'
    | '/insurance/$id'
    | '/tickets/$id'
    | '/tours/$id'
    | '/visa/$id'
    | '/insurance'
    | '/tickets'
    | '/tours'
    | '/visa'
    | '/admin/affiliate-payouts'
    | '/admin/affiliates'
    | '/admin/ai'
    | '/admin/custom-leads'
    | '/admin/custom-visa'
    | '/admin/financials'
    | '/admin/kyc-cms'
    | '/admin/landing-cms'
    | '/admin/leads'
    | '/admin/payments'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/subscriptions'
    | '/admin/tours'
    | '/admin/users'
    | '/admin/vendor-guide'
    | '/admin/vendors'
    | '/admin/whatsapp'
    | '/vendor/billing'
    | '/vendor/custom-leads'
    | '/vendor/custom-visa-leads'
    | '/vendor/insurance'
    | '/vendor/invoices'
    | '/vendor/kyc'
    | '/vendor/leads'
    | '/vendor/services'
    | '/vendor/tickets'
    | '/vendor/tours'
    | '/vendor/visa'
    | '/api/auth/register'
    | '/api/cron/subscriptions'
    | '/api/public/safepay-webhook'
    | '/admin'
    | '/customer'
    | '/vendor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/affiliate'
    | '/auth'
    | '/become-affiliate'
    | '/compare'
    | '/custom-tour'
    | '/custom-visa'
    | '/destinations'
    | '/enterprise'
    | '/insurance'
    | '/pricing'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/tickets'
    | '/tours'
    | '/vendor-guide'
    | '/visa'
    | '/wishlist'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/vendor'
    | '/api/ai-chat'
    | '/api/sitemap.xml'
    | '/customer/quotes'
    | '/customer/visa-quotes'
    | '/insurance/$id'
    | '/tickets/$id'
    | '/tours/$id'
    | '/visa/$id'
    | '/insurance/'
    | '/tickets/'
    | '/tours/'
    | '/visa/'
    | '/_authenticated/admin/affiliate-payouts'
    | '/_authenticated/admin/affiliates'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/custom-leads'
    | '/_authenticated/admin/custom-visa'
    | '/_authenticated/admin/financials'
    | '/_authenticated/admin/kyc-cms'
    | '/_authenticated/admin/landing-cms'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/seo'
    | '/_authenticated/admin/services'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/tours'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/vendor-guide'
    | '/_authenticated/admin/vendors'
    | '/_authenticated/admin/whatsapp'
    | '/_authenticated/vendor/billing'
    | '/_authenticated/vendor/custom-leads'
    | '/_authenticated/vendor/custom-visa-leads'
    | '/_authenticated/vendor/insurance'
    | '/_authenticated/vendor/invoices'
    | '/_authenticated/vendor/kyc'
    | '/_authenticated/vendor/leads'
    | '/_authenticated/vendor/services'
    | '/_authenticated/vendor/tickets'
    | '/_authenticated/vendor/tours'
    | '/_authenticated/vendor/visa'
    | '/api/auth/register'
    | '/api/cron/subscriptions'
    | '/api/public/safepay-webhook'
    | '/_authenticated/admin/'
    | '/_authenticated/customer/'
    | '/_authenticated/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AffiliateRoute: typeof AffiliateRoute
  AuthRoute: typeof AuthRoute
  BecomeAffiliateRoute: typeof BecomeAffiliateRoute
  CompareRoute: typeof CompareRoute
  CustomTourRoute: typeof CustomTourRoute
  CustomVisaRoute: typeof CustomVisaRoute
  DestinationsRoute: typeof DestinationsRoute
  EnterpriseRoute: typeof EnterpriseRoute
  InsuranceRoute: typeof InsuranceRouteWithChildren
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TicketsRoute: typeof TicketsRouteWithChildren
  ToursRoute: typeof ToursRouteWithChildren
  VendorGuideRoute: typeof VendorGuideRoute
  VisaRoute: typeof VisaRouteWithChildren
  WishlistRoute: typeof WishlistRoute
  ApiAiChatRoute: typeof ApiAiChatRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  CustomerQuotesRoute: typeof CustomerQuotesRoute
  CustomerVisaQuotesRoute: typeof CustomerVisaQuotesRoute
  ApiAuthRegisterRoute: typeof ApiAuthRegisterRoute
  ApiCronSubscriptionsRoute: typeof ApiCronSubscriptionsRoute
  ApiPublicSafepayWebhookRoute: typeof ApiPublicSafepayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate': {
      id: '/affiliate'
      path: '/affiliate'
      fullPath: '/affiliate'
      preLoaderRoute: typeof AffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-affiliate': {
      id: '/become-affiliate'
      path: '/become-affiliate'
      fullPath: '/become-affiliate'
      preLoaderRoute: typeof BecomeAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-tour': {
      id: '/custom-tour'
      path: '/custom-tour'
      fullPath: '/custom-tour'
      preLoaderRoute: typeof CustomTourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-visa': {
      id: '/custom-visa'
      path: '/custom-visa'
      fullPath: '/custom-visa'
      preLoaderRoute: typeof CustomVisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours': {
      id: '/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof ToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-guide': {
      id: '/vendor-guide'
      path: '/vendor-guide'
      fullPath: '/vendor-guide'
      preLoaderRoute: typeof VendorGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor': {
      id: '/_authenticated/vendor'
      path: '/vendor'
      fullPath: '/vendor'
      preLoaderRoute: typeof AuthenticatedVendorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ai-chat': {
      id: '/api/ai-chat'
      path: '/api/ai-chat'
      fullPath: '/api/ai-chat'
      preLoaderRoute: typeof ApiAiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/quotes': {
      id: '/customer/quotes'
      path: '/customer/quotes'
      fullPath: '/customer/quotes'
      preLoaderRoute: typeof CustomerQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/visa-quotes': {
      id: '/customer/visa-quotes'
      path: '/customer/visa-quotes'
      fullPath: '/customer/visa-quotes'
      preLoaderRoute: typeof CustomerVisaQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/': {
      id: '/insurance/'
      path: '/'
      fullPath: '/insurance/'
      preLoaderRoute: typeof InsuranceIndexRouteImport
      parentRoute: typeof InsuranceRoute
    }
    '/insurance/$id': {
      id: '/insurance/$id'
      path: '/$id'
      fullPath: '/insurance/$id'
      preLoaderRoute: typeof InsuranceIdRouteImport
      parentRoute: typeof InsuranceRoute
    }
    '/tickets/': {
      id: '/tickets/'
      path: '/'
      fullPath: '/tickets/'
      preLoaderRoute: typeof TicketsIndexRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tickets/$id': {
      id: '/tickets/$id'
      path: '/$id'
      fullPath: '/tickets/$id'
      preLoaderRoute: typeof TicketsIdRouteImport
      parentRoute: typeof TicketsRoute
    }
    '/tours/': {
      id: '/tours/'
      path: '/'
      fullPath: '/tours/'
      preLoaderRoute: typeof ToursIndexRouteImport
      parentRoute: typeof ToursRoute
    }
    '/tours/$id': {
      id: '/tours/$id'
      path: '/$id'
      fullPath: '/tours/$id'
      preLoaderRoute: typeof ToursIdRouteImport
      parentRoute: typeof ToursRoute
    }
    '/visa/': {
      id: '/visa/'
      path: '/'
      fullPath: '/visa/'
      preLoaderRoute: typeof VisaIndexRouteImport
      parentRoute: typeof VisaRoute
    }
    '/visa/$id': {
      id: '/visa/$id'
      path: '/$id'
      fullPath: '/visa/$id'
      preLoaderRoute: typeof VisaIdRouteImport
      parentRoute: typeof VisaRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/affiliate-payouts': {
      id: '/_authenticated/admin/affiliate-payouts'
      path: '/affiliate-payouts'
      fullPath: '/admin/affiliate-payouts'
      preLoaderRoute: typeof AuthenticatedAdminAffiliatePayoutsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/affiliates': {
      id: '/_authenticated/admin/affiliates'
      path: '/affiliates'
      fullPath: '/admin/affiliates'
      preLoaderRoute: typeof AuthenticatedAdminAffiliatesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/custom-leads': {
      id: '/_authenticated/admin/custom-leads'
      path: '/custom-leads'
      fullPath: '/admin/custom-leads'
      preLoaderRoute: typeof AuthenticatedAdminCustomLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/custom-visa': {
      id: '/_authenticated/admin/custom-visa'
      path: '/custom-visa'
      fullPath: '/admin/custom-visa'
      preLoaderRoute: typeof AuthenticatedAdminCustomVisaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/financials': {
      id: '/_authenticated/admin/financials'
      path: '/financials'
      fullPath: '/admin/financials'
      preLoaderRoute: typeof AuthenticatedAdminFinancialsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/kyc-cms': {
      id: '/_authenticated/admin/kyc-cms'
      path: '/kyc-cms'
      fullPath: '/admin/kyc-cms'
      preLoaderRoute: typeof AuthenticatedAdminKycCmsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/landing-cms': {
      id: '/_authenticated/admin/landing-cms'
      path: '/landing-cms'
      fullPath: '/admin/landing-cms'
      preLoaderRoute: typeof AuthenticatedAdminLandingCmsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/seo': {
      id: '/_authenticated/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/services': {
      id: '/_authenticated/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AuthenticatedAdminServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tours': {
      id: '/_authenticated/admin/tours'
      path: '/tours'
      fullPath: '/admin/tours'
      preLoaderRoute: typeof AuthenticatedAdminToursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vendor-guide': {
      id: '/_authenticated/admin/vendor-guide'
      path: '/vendor-guide'
      fullPath: '/admin/vendor-guide'
      preLoaderRoute: typeof AuthenticatedAdminVendorGuideRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/vendors': {
      id: '/_authenticated/admin/vendors'
      path: '/vendors'
      fullPath: '/admin/vendors'
      preLoaderRoute: typeof AuthenticatedAdminVendorsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/whatsapp': {
      id: '/_authenticated/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AuthenticatedAdminWhatsappRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/customer/': {
      id: '/_authenticated/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof AuthenticatedCustomerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendor/': {
      id: '/_authenticated/vendor/'
      path: '/'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AuthenticatedVendorIndexRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/billing': {
      id: '/_authenticated/vendor/billing'
      path: '/billing'
      fullPath: '/vendor/billing'
      preLoaderRoute: typeof AuthenticatedVendorBillingRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/custom-leads': {
      id: '/_authenticated/vendor/custom-leads'
      path: '/custom-leads'
      fullPath: '/vendor/custom-leads'
      preLoaderRoute: typeof AuthenticatedVendorCustomLeadsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/custom-visa-leads': {
      id: '/_authenticated/vendor/custom-visa-leads'
      path: '/custom-visa-leads'
      fullPath: '/vendor/custom-visa-leads'
      preLoaderRoute: typeof AuthenticatedVendorCustomVisaLeadsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/insurance': {
      id: '/_authenticated/vendor/insurance'
      path: '/insurance'
      fullPath: '/vendor/insurance'
      preLoaderRoute: typeof AuthenticatedVendorInsuranceRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/invoices': {
      id: '/_authenticated/vendor/invoices'
      path: '/invoices'
      fullPath: '/vendor/invoices'
      preLoaderRoute: typeof AuthenticatedVendorInvoicesRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/kyc': {
      id: '/_authenticated/vendor/kyc'
      path: '/kyc'
      fullPath: '/vendor/kyc'
      preLoaderRoute: typeof AuthenticatedVendorKycRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/leads': {
      id: '/_authenticated/vendor/leads'
      path: '/leads'
      fullPath: '/vendor/leads'
      preLoaderRoute: typeof AuthenticatedVendorLeadsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/services': {
      id: '/_authenticated/vendor/services'
      path: '/services'
      fullPath: '/vendor/services'
      preLoaderRoute: typeof AuthenticatedVendorServicesRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/tickets': {
      id: '/_authenticated/vendor/tickets'
      path: '/tickets'
      fullPath: '/vendor/tickets'
      preLoaderRoute: typeof AuthenticatedVendorTicketsRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/tours': {
      id: '/_authenticated/vendor/tours'
      path: '/tours'
      fullPath: '/vendor/tours'
      preLoaderRoute: typeof AuthenticatedVendorToursRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/_authenticated/vendor/visa': {
      id: '/_authenticated/vendor/visa'
      path: '/visa'
      fullPath: '/vendor/visa'
      preLoaderRoute: typeof AuthenticatedVendorVisaRouteImport
      parentRoute: typeof AuthenticatedVendorRoute
    }
    '/api/auth/register': {
      id: '/api/auth/register'
      path: '/api/auth/register'
      fullPath: '/api/auth/register'
      preLoaderRoute: typeof ApiAuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/subscriptions': {
      id: '/api/cron/subscriptions'
      path: '/api/cron/subscriptions'
      fullPath: '/api/cron/subscriptions'
      preLoaderRoute: typeof ApiCronSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/safepay-webhook': {
      id: '/api/public/safepay-webhook'
      path: '/api/public/safepay-webhook'
      fullPath: '/api/public/safepay-webhook'
      preLoaderRoute: typeof ApiPublicSafepayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAffiliatePayoutsRoute: typeof AuthenticatedAdminAffiliatePayoutsRoute
  AuthenticatedAdminAffiliatesRoute: typeof AuthenticatedAdminAffiliatesRoute
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminCustomLeadsRoute: typeof AuthenticatedAdminCustomLeadsRoute
  AuthenticatedAdminCustomVisaRoute: typeof AuthenticatedAdminCustomVisaRoute
  AuthenticatedAdminFinancialsRoute: typeof AuthenticatedAdminFinancialsRoute
  AuthenticatedAdminKycCmsRoute: typeof AuthenticatedAdminKycCmsRoute
  AuthenticatedAdminLandingCmsRoute: typeof AuthenticatedAdminLandingCmsRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminSeoRoute: typeof AuthenticatedAdminSeoRoute
  AuthenticatedAdminServicesRoute: typeof AuthenticatedAdminServicesRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminToursRoute: typeof AuthenticatedAdminToursRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVendorGuideRoute: typeof AuthenticatedAdminVendorGuideRoute
  AuthenticatedAdminVendorsRoute: typeof AuthenticatedAdminVendorsRoute
  AuthenticatedAdminWhatsappRoute: typeof AuthenticatedAdminWhatsappRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAffiliatePayoutsRoute:
    AuthenticatedAdminAffiliatePayoutsRoute,
  AuthenticatedAdminAffiliatesRoute: AuthenticatedAdminAffiliatesRoute,
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminCustomLeadsRoute: AuthenticatedAdminCustomLeadsRoute,
  AuthenticatedAdminCustomVisaRoute: AuthenticatedAdminCustomVisaRoute,
  AuthenticatedAdminFinancialsRoute: AuthenticatedAdminFinancialsRoute,
  AuthenticatedAdminKycCmsRoute: AuthenticatedAdminKycCmsRoute,
  AuthenticatedAdminLandingCmsRoute: AuthenticatedAdminLandingCmsRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminSeoRoute: AuthenticatedAdminSeoRoute,
  AuthenticatedAdminServicesRoute: AuthenticatedAdminServicesRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminToursRoute: AuthenticatedAdminToursRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVendorGuideRoute: AuthenticatedAdminVendorGuideRoute,
  AuthenticatedAdminVendorsRoute: AuthenticatedAdminVendorsRoute,
  AuthenticatedAdminWhatsappRoute: AuthenticatedAdminWhatsappRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedVendorRouteChildren {
  AuthenticatedVendorBillingRoute: typeof AuthenticatedVendorBillingRoute
  AuthenticatedVendorCustomLeadsRoute: typeof AuthenticatedVendorCustomLeadsRoute
  AuthenticatedVendorCustomVisaLeadsRoute: typeof AuthenticatedVendorCustomVisaLeadsRoute
  AuthenticatedVendorInsuranceRoute: typeof AuthenticatedVendorInsuranceRoute
  AuthenticatedVendorInvoicesRoute: typeof AuthenticatedVendorInvoicesRoute
  AuthenticatedVendorKycRoute: typeof AuthenticatedVendorKycRoute
  AuthenticatedVendorLeadsRoute: typeof AuthenticatedVendorLeadsRoute
  AuthenticatedVendorServicesRoute: typeof AuthenticatedVendorServicesRoute
  AuthenticatedVendorTicketsRoute: typeof AuthenticatedVendorTicketsRoute
  AuthenticatedVendorToursRoute: typeof AuthenticatedVendorToursRoute
  AuthenticatedVendorVisaRoute: typeof AuthenticatedVendorVisaRoute
  AuthenticatedVendorIndexRoute: typeof AuthenticatedVendorIndexRoute
}

const AuthenticatedVendorRouteChildren: AuthenticatedVendorRouteChildren = {
  AuthenticatedVendorBillingRoute: AuthenticatedVendorBillingRoute,
  AuthenticatedVendorCustomLeadsRoute: AuthenticatedVendorCustomLeadsRoute,
  AuthenticatedVendorCustomVisaLeadsRoute:
    AuthenticatedVendorCustomVisaLeadsRoute,
  AuthenticatedVendorInsuranceRoute: AuthenticatedVendorInsuranceRoute,
  AuthenticatedVendorInvoicesRoute: AuthenticatedVendorInvoicesRoute,
  AuthenticatedVendorKycRoute: AuthenticatedVendorKycRoute,
  AuthenticatedVendorLeadsRoute: AuthenticatedVendorLeadsRoute,
  AuthenticatedVendorServicesRoute: AuthenticatedVendorServicesRoute,
  AuthenticatedVendorTicketsRoute: AuthenticatedVendorTicketsRoute,
  AuthenticatedVendorToursRoute: AuthenticatedVendorToursRoute,
  AuthenticatedVendorVisaRoute: AuthenticatedVendorVisaRoute,
  AuthenticatedVendorIndexRoute: AuthenticatedVendorIndexRoute,
}

const AuthenticatedVendorRouteWithChildren =
  AuthenticatedVendorRoute._addFileChildren(AuthenticatedVendorRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedVendorRoute: typeof AuthenticatedVendorRouteWithChildren
  AuthenticatedCustomerIndexRoute: typeof AuthenticatedCustomerIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedVendorRoute: AuthenticatedVendorRouteWithChildren,
  AuthenticatedCustomerIndexRoute: AuthenticatedCustomerIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface InsuranceRouteChildren {
  InsuranceIdRoute: typeof InsuranceIdRoute
  InsuranceIndexRoute: typeof InsuranceIndexRoute
}

const InsuranceRouteChildren: InsuranceRouteChildren = {
  InsuranceIdRoute: InsuranceIdRoute,
  InsuranceIndexRoute: InsuranceIndexRoute,
}

const InsuranceRouteWithChildren = InsuranceRoute._addFileChildren(
  InsuranceRouteChildren,
)

interface TicketsRouteChildren {
  TicketsIdRoute: typeof TicketsIdRoute
  TicketsIndexRoute: typeof TicketsIndexRoute
}

const TicketsRouteChildren: TicketsRouteChildren = {
  TicketsIdRoute: TicketsIdRoute,
  TicketsIndexRoute: TicketsIndexRoute,
}

const TicketsRouteWithChildren =
  TicketsRoute._addFileChildren(TicketsRouteChildren)

interface ToursRouteChildren {
  ToursIdRoute: typeof ToursIdRoute
  ToursIndexRoute: typeof ToursIndexRoute
}

const ToursRouteChildren: ToursRouteChildren = {
  ToursIdRoute: ToursIdRoute,
  ToursIndexRoute: ToursIndexRoute,
}

const ToursRouteWithChildren = ToursRoute._addFileChildren(ToursRouteChildren)

interface VisaRouteChildren {
  VisaIdRoute: typeof VisaIdRoute
  VisaIndexRoute: typeof VisaIndexRoute
}

const VisaRouteChildren: VisaRouteChildren = {
  VisaIdRoute: VisaIdRoute,
  VisaIndexRoute: VisaIndexRoute,
}

const VisaRouteWithChildren = VisaRoute._addFileChildren(VisaRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AffiliateRoute: AffiliateRoute,
  AuthRoute: AuthRoute,
  BecomeAffiliateRoute: BecomeAffiliateRoute,
  CompareRoute: CompareRoute,
  CustomTourRoute: CustomTourRoute,
  CustomVisaRoute: CustomVisaRoute,
  DestinationsRoute: DestinationsRoute,
  EnterpriseRoute: EnterpriseRoute,
  InsuranceRoute: InsuranceRouteWithChildren,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TicketsRoute: TicketsRouteWithChildren,
  ToursRoute: ToursRouteWithChildren,
  VendorGuideRoute: VendorGuideRoute,
  VisaRoute: VisaRouteWithChildren,
  WishlistRoute: WishlistRoute,
  ApiAiChatRoute: ApiAiChatRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  CustomerQuotesRoute: CustomerQuotesRoute,
  CustomerVisaQuotesRoute: CustomerVisaQuotesRoute,
  ApiAuthRegisterRoute: ApiAuthRegisterRoute,
  ApiCronSubscriptionsRoute: ApiCronSubscriptionsRoute,
  ApiPublicSafepayWebhookRoute: ApiPublicSafepayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
